### ISSUE TITLE
CA1 -H4: Como usuaria quiero poder ordenar de manera ascendente (menor a mayor) o descendente (mayor a menor) a los pokemones -Spawns

### ISSUE THREAD

**Issue by ElizabethCO25** [Betsycaceres/LIM010-data-lovers#29]
Como usuaria quiero poder ordenar  de manera ascendente (menor a mayor) o descendente (mayor a menor) a los pokemones

**Comment by Betsycaceres** [comment]
Usuario puede ordenar alfabéticamente de manera ascendente y descendente según frecuencia de aparición.
