### ISSUE TITLE
CA 1 - H5: Como usuaria quiero poder filtrar a los pokemones por debilidades para saber quiénes tienen esa debilidad.

### ISSUE THREAD

**Issue by ElizabethCO25** [Betsycaceres/LIM010-data-lovers#31]
Como usuaria quiero poder filtrar a los pokemones por debilidades para saber quiénes  tienen esa debilidad.

**Comment by Betsycaceres** [comment]
Usuario puede  filtrar a los pokemon segùn su debilidad.
