### ISSUE TITLE
CA2-H5: Como usuaria quiero poder filtrar a los pokemones por tipo para saber quiénes y cuántos son de cada tipo.

### ISSUE THREAD

**Issue by ElizabethCO25** [Betsycaceres/LIM010-data-lovers#32]
Como usuaria quiero poder filtrar a los pokemones por tipo para saber quiénes y cuántos son de cada tipo.

**Comment by Betsycaceres** [comment]
Usuario puede  filtrar a los pokemon segùn su  tipo.
