### ISSUE TITLE
CA-2: Luego de 3 intentos se bloquea la opción para seguir intentado.

### ISSUE THREAD

**Issue by ElizabethCO25** [Betsycaceres/LIM010-data-lovers#4]
- [x] Implementar contador de intentos.
- [x] Implementar pantalla de bloqueo
   - [x] Agregar imagen (css)
   - [x] Mostrar texto de error (html css)

**Comment by Betsycaceres** [comment]
se muestra pantalla de bloqueo despuès de tres intentos erróneos.
