### ISSUE TITLE
CA -1: Usuaria puede acceder con el usuario y clave facilitados.

### ISSUE THREAD

**Issue by ElizabethCO25** [Betsycaceres/LIM010-data-lovers#5]
- [x] Insertar imagen de logo (html y css)
- [x] Implementar los labels (html y css)
- [x] Implementar los inputs (html y css)
- [x] Implementar botón (html y css)
- [x] Implementar funcion para mostrar sig pantalla

**Comment by Betsycaceres** [comment]
usuario puede  ingresar a la web con la palabra "LABORATORIA" como correo electrònico y contraseña.
